// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(StackCoreRustFFI)
import StackCoreRustFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_stack_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_stack_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureStackCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Secure-credential storage implemented natively (Keychain on iOS) and injected
 * across the FFI boundary as a foreign trait. Each provider declares the keys it
 * reads via its `credential_schema` (see `service::registry`).
 */
public protocol CredentialStore: AnyObject, Sendable {
    
    /**
     * Returns the secret stored for `(account_id, key)`, if present.
     */
    func secret(accountId: String, key: String)  -> String?
    
    /**
     * Stores or replaces a secret.
     */
    func setSecret(accountId: String, key: String, value: String) 
    
    /**
     * Removes every secret associated with `account_id`.
     */
    func delete(accountId: String) 
    
}
/**
 * Secure-credential storage implemented natively (Keychain on iOS) and injected
 * across the FFI boundary as a foreign trait. Each provider declares the keys it
 * reads via its `credential_schema` (see `service::registry`).
 */
open class CredentialStoreImpl: CredentialStore, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_stack_core_fn_clone_credentialstore(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_stack_core_fn_free_credentialstore(handle, $0) }
    }

    

    
    /**
     * Returns the secret stored for `(account_id, key)`, if present.
     */
open func secret(accountId: String, key: String) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_stack_core_fn_method_credentialstore_secret(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(accountId),
        FfiConverterString.lower(key),$0
    )
})
}
    
    /**
     * Stores or replaces a secret.
     */
open func setSecret(accountId: String, key: String, value: String)  {try! rustCall() {
    uniffi_stack_core_fn_method_credentialstore_set_secret(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(accountId),
        FfiConverterString.lower(key),
        FfiConverterString.lower(value),$0
    )
}
}
    
    /**
     * Removes every secret associated with `account_id`.
     */
open func delete(accountId: String)  {try! rustCall() {
    uniffi_stack_core_fn_method_credentialstore_delete(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(accountId),$0
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceCredentialStore {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceCredentialStore = UniffiVTableCallbackInterfaceCredentialStore(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeCredentialStore.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface CredentialStore: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeCredentialStore.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface CredentialStore: handle missing in uniffiClone")
            }
        },
        secret: { (
            uniffiHandle: UInt64,
            accountId: RustBuffer,
            key: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String? in
                guard let uniffiObj = try? FfiConverterTypeCredentialStore.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.secret(
                     accountId: try FfiConverterString.lift(accountId),
                     key: try FfiConverterString.lift(key)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterOptionString.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        setSecret: { (
            uniffiHandle: UInt64,
            accountId: RustBuffer,
            key: RustBuffer,
            value: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeCredentialStore.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.setSecret(
                     accountId: try FfiConverterString.lift(accountId),
                     key: try FfiConverterString.lift(key),
                     value: try FfiConverterString.lift(value)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        delete: { (
            uniffiHandle: UInt64,
            accountId: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeCredentialStore.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.delete(
                     accountId: try FfiConverterString.lift(accountId)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceCredentialStore> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceCredentialStore>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitCredentialStore() {
    uniffi_stack_core_fn_init_callback_vtable_credentialstore(UniffiCallbackInterfaceCredentialStore.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCredentialStore: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<CredentialStore>()

    typealias FfiType = UInt64
    typealias SwiftType = CredentialStore

    public static func lift(_ handle: UInt64) throws -> CredentialStore {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return CredentialStoreImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: CredentialStore) -> UInt64 {
         if let rustImpl = value as? CredentialStoreImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CredentialStore {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CredentialStore, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCredentialStore_lift(_ handle: UInt64) throws -> CredentialStore {
    return try FfiConverterTypeCredentialStore.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCredentialStore_lower(_ value: CredentialStore) -> UInt64 {
    return FfiConverterTypeCredentialStore.lower(value)
}






/**
 * UniFFI-exported provider handle. A thin, binding-friendly wrapper around a
 * boxed [`ProviderImpl`]: synchronous metadata is exported directly, async work
 * runs on the tokio runtime. Adding a *service* never changes this surface —
 * only adding a *capability* would add a method here.
 */
public protocol ProviderProtocol: AnyObject, Sendable {
    
    /**
     * The capabilities exposed for the connected account.
     */
    func capabilities()  -> [Capability]
    
    /**
     * Lists the apps visible to the connected account.
     *
     * # Errors
     * [`StackError::Unsupported`] if the provider lacks [`Capability::Apps`];
     * otherwise a transport, HTTP, or decoding error.
     */
    func fetchApps() async throws  -> [AppInfo]
    
    /**
     * Which service this provider speaks to.
     */
    func kind()  -> ServiceKind
    
    /**
     * Verifies the stored credentials against the live service.
     *
     * # Errors
     * [`StackError::Auth`] when the credentials are rejected (including App Store
     * Connect "pending agreements"), or a transport/decoding error.
     */
    func validate() async throws 
    
}
/**
 * UniFFI-exported provider handle. A thin, binding-friendly wrapper around a
 * boxed [`ProviderImpl`]: synchronous metadata is exported directly, async work
 * runs on the tokio runtime. Adding a *service* never changes this surface —
 * only adding a *capability* would add a method here.
 */
open class Provider: ProviderProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_stack_core_fn_clone_provider(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_stack_core_fn_free_provider(handle, $0) }
    }

    

    
    /**
     * The capabilities exposed for the connected account.
     */
open func capabilities() -> [Capability]  {
    return try!  FfiConverterSequenceTypeCapability.lift(try! rustCall() {
    uniffi_stack_core_fn_method_provider_capabilities(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Lists the apps visible to the connected account.
     *
     * # Errors
     * [`StackError::Unsupported`] if the provider lacks [`Capability::Apps`];
     * otherwise a transport, HTTP, or decoding error.
     */
open func fetchApps()async throws  -> [AppInfo]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_stack_core_fn_method_provider_fetch_apps(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_stack_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_stack_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_stack_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeAppInfo.lift,
            errorHandler: FfiConverterTypeStackError_lift
        )
}
    
    /**
     * Which service this provider speaks to.
     */
open func kind() -> ServiceKind  {
    return try!  FfiConverterTypeServiceKind_lift(try! rustCall() {
    uniffi_stack_core_fn_method_provider_kind(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Verifies the stored credentials against the live service.
     *
     * # Errors
     * [`StackError::Auth`] when the credentials are rejected (including App Store
     * Connect "pending agreements"), or a transport/decoding error.
     */
open func validate()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_stack_core_fn_method_provider_validate(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_stack_core_rust_future_poll_void,
            completeFunc: ffi_stack_core_rust_future_complete_void,
            freeFunc: ffi_stack_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeStackError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProvider: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Provider

    public static func lift(_ handle: UInt64) throws -> Provider {
        return Provider(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Provider) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Provider {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Provider, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProvider_lift(_ handle: UInt64) throws -> Provider {
    return try FfiConverterTypeProvider.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProvider_lower(_ value: Provider) -> UInt64 {
    return FfiConverterTypeProvider.lower(value)
}




/**
 * Cross-provider app metadata. Mirrors the Swift `AppInfo` from `StackProtocols`,
 * which is dissolved into the core (see RUST_CORE_PLAN.md §4).
 */
public struct AppInfo: Equatable, Hashable {
    public var id: String
    public var name: String
    public var bundleId: String
    public var platform: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, bundleId: String, platform: String?) {
        self.id = id
        self.name = name
        self.bundleId = bundleId
        self.platform = platform
    }

    

    
}

#if compiler(>=6)
extension AppInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAppInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AppInfo {
        return
            try AppInfo(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                bundleId: FfiConverterString.read(from: &buf), 
                platform: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: AppInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.bundleId, into: &buf)
        FfiConverterOptionString.write(value.platform, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppInfo_lift(_ buf: RustBuffer) throws -> AppInfo {
    return try FfiConverterTypeAppInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppInfo_lower(_ value: AppInfo) -> RustBuffer {
    return FfiConverterTypeAppInfo.lower(value)
}


/**
 * A single credential field a service requires. Drives the host's "connect
 * account" form: `label` is shown to the user, `secret` hides the input, and
 * `multiline` signals a textarea (e.g. a PEM-encoded private key).
 */
public struct CredentialField: Equatable, Hashable {
    public var key: String
    public var label: String
    public var secret: Bool
    public var multiline: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String, label: String, secret: Bool, multiline: Bool) {
        self.key = key
        self.label = label
        self.secret = secret
        self.multiline = multiline
    }

    

    
}

#if compiler(>=6)
extension CredentialField: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCredentialField: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CredentialField {
        return
            try CredentialField(
                key: FfiConverterString.read(from: &buf), 
                label: FfiConverterString.read(from: &buf), 
                secret: FfiConverterBool.read(from: &buf), 
                multiline: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: CredentialField, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterBool.write(value.secret, into: &buf)
        FfiConverterBool.write(value.multiline, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCredentialField_lift(_ buf: RustBuffer) throws -> CredentialField {
    return try FfiConverterTypeCredentialField.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCredentialField_lower(_ value: CredentialField) -> RustBuffer {
    return FfiConverterTypeCredentialField.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * A capability a provider may expose. The host calls [`Provider::capabilities`]
 * to learn what a connected account can do; capabilities a provider lacks make
 * the corresponding methods return [`StackError::Unsupported`]. Grows over time.
 */

public enum Capability: Equatable, Hashable {
    
    case apps





}

#if compiler(>=6)
extension Capability: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCapability: FfiConverterRustBuffer {
    typealias SwiftType = Capability

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Capability {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .apps
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Capability, into buf: inout [UInt8]) {
        switch value {
        
        
        case .apps:
            writeInt(&buf, Int32(1))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCapability_lift(_ buf: RustBuffer) throws -> Capability {
    return try FfiConverterTypeCapability.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCapability_lower(_ value: Capability) -> RustBuffer {
    return FfiConverterTypeCapability.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Which external service a connected account talks to. Exported across the FFI;
 * designed to grow as new plugins land (Firebase, Google Play, AWS, GitHub, …).
 */

public enum ServiceKind: Equatable, Hashable {
    
    case appStoreConnect





}

#if compiler(>=6)
extension ServiceKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeServiceKind: FfiConverterRustBuffer {
    typealias SwiftType = ServiceKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ServiceKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .appStoreConnect
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ServiceKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .appStoreConnect:
            writeInt(&buf, Int32(1))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeServiceKind_lift(_ buf: RustBuffer) throws -> ServiceKind {
    return try FfiConverterTypeServiceKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeServiceKind_lower(_ value: ServiceKind) -> RustBuffer {
    return FfiConverterTypeServiceKind.lower(value)
}



/**
 * Errors that cross the FFI boundary. Every variant carries only FFI-safe fields
 * (strings, integers) so UniFFI can marshal the associated values to Swift.
 */
public enum StackError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case InvalidCredentials(message: String
    )
    case Auth(message: String
    )
    case Http(status: UInt16, message: String
    )
    case Decode(message: String
    )
    case Network(message: String
    )
    case Unsupported(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension StackError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStackError: FfiConverterRustBuffer {
    typealias SwiftType = StackError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StackError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidCredentials(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Auth(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Http(
            status: try FfiConverterUInt16.read(from: &buf), 
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Decode(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Network(
            message: try FfiConverterString.read(from: &buf)
            )
        case 6: return .Unsupported(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StackError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidCredentials(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Auth(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Http(status,message):
            writeInt(&buf, Int32(3))
            FfiConverterUInt16.write(status, into: &buf)
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Decode(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Network(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Unsupported(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStackError_lift(_ buf: RustBuffer) throws -> StackError {
    return try FfiConverterTypeStackError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStackError_lower(_ value: StackError) -> RustBuffer {
    return FfiConverterTypeStackError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAppInfo: FfiConverterRustBuffer {
    typealias SwiftType = [AppInfo]

    public static func write(_ value: [AppInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAppInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AppInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [AppInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAppInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCredentialField: FfiConverterRustBuffer {
    typealias SwiftType = [CredentialField]

    public static func write(_ value: [CredentialField], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCredentialField.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CredentialField] {
        let len: Int32 = try readInt(&buf)
        var seq = [CredentialField]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCredentialField.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCapability: FfiConverterRustBuffer {
    typealias SwiftType = [Capability]

    public static func write(_ value: [Capability], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCapability.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Capability] {
        let len: Int32 = try readInt(&buf)
        var seq = [Capability]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCapability.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeServiceKind: FfiConverterRustBuffer {
    typealias SwiftType = [ServiceKind]

    public static func write(_ value: [ServiceKind], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeServiceKind.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ServiceKind] {
        let len: Int32 = try readInt(&buf)
        var seq = [ServiceKind]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeServiceKind.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureStackCoreInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * Every service the core can connect today. Drives the host's service picker.
 */
public func availableServices() -> [ServiceKind]  {
    return try!  FfiConverterSequenceTypeServiceKind.lift(try! rustCall() {
    uniffi_stack_core_fn_func_available_services($0
    )
})
}
/**
 * Reads the secrets for `(kind, account_id)` from the host `store` and builds a
 * connected [`Provider`].
 *
 * Synchronous on purpose: it only reads secrets through the (synchronous)
 * callback and parses the key material — no network. The returned provider does
 * the async work (`validate`, `fetch_apps`).
 *
 * # Errors
 * [`StackError::InvalidCredentials`] if a required secret is missing.
 */
public func connect(kind: ServiceKind, accountId: String, store: CredentialStore)throws  -> Provider  {
    return try  FfiConverterTypeProvider_lift(try rustCallWithError(FfiConverterTypeStackError_lift) {
    uniffi_stack_core_fn_func_connect(
        FfiConverterTypeServiceKind_lower(kind),
        FfiConverterString.lower(accountId),
        FfiConverterTypeCredentialStore_lower(store),$0
    )
})
}
/**
 * The credential form the host should render to connect an account of `kind`.
 */
public func credentialSchema(kind: ServiceKind) -> [CredentialField]  {
    return try!  FfiConverterSequenceTypeCredentialField.lift(try! rustCall() {
    uniffi_stack_core_fn_func_credential_schema(
        FfiConverterTypeServiceKind_lower(kind),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_stack_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_stack_core_checksum_func_available_services() != 22553) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stack_core_checksum_func_connect() != 14672) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stack_core_checksum_func_credential_schema() != 9978) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stack_core_checksum_method_credentialstore_secret() != 28669) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stack_core_checksum_method_credentialstore_set_secret() != 6859) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stack_core_checksum_method_credentialstore_delete() != 36020) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stack_core_checksum_method_provider_capabilities() != 53465) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stack_core_checksum_method_provider_fetch_apps() != 36949) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stack_core_checksum_method_provider_kind() != 47339) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_stack_core_checksum_method_provider_validate() != 51064) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitCredentialStore()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureStackCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all